### ISSUE TITLE
Business lines TemplateDoesNotExist

### ISSUE THREAD

**Issue by benjimons** [certsocietegenerale/FIR#140]
When trying to access /admin/incidents/businessline/

a 500 error occurs, the output form the following is thrown into the logs

```
2016-11-25 23:20:29,502: base base.py:284(handle_uncaught_exception)
Internal Server Error: /admin/incidents/businessline/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 82, in resolve_template
    return get_template(template, using=self.using)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: admin/tree_change_list.html
```

**Comment by tomchop** [comment]
Fixed in b46d286dac03484753cfc28952d0df78cd01390e
