### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by keoni161** [certsocietegenerale/FIR#147]
Hi,
We have made a fresh install and wanted to import the incidents from the old application,
After the install, we can no longer see incidents/events and some reports
[errors.txt](https://github.com/certsocietegenerale/FIR/files/657306/errors.txt)

Can you help us or provide a hint for successfully upgrade-ing or importing historical data?
Thank you
Claudiu

**Comment by josarsepi** [comment]
Keoni it may work better to upgrade the original/old application.

I had an issue updating to the latest version as well but resolved the issue using the data in this (https://github.com/certsocietegenerale/FIR/issues/146) issue post without any data loss.

**Comment by gcrahay** [comment]
Hi,

FIR is a Django app and comes with its data model and data migration scripts. You should upgrade the FIR application *in place*. Data from an old version may be incompatible with a newer version. So @josarsepi is right: you should upgrade the original application before exporting data and importing into the new application.

**Comment by keoni161** [comment]
Good evening.
Thank you all for your help.
I have tried an in-place upgrade but unfortunately when we tried to apply migrations we encountered errors because it could not create some of the tables.
I will try again on Monday and post the error.
Have a pleasant weekend
Claudiu

**Comment by keoni161** [comment]
Good morning all,
Like I said, i have retried the upgrade in-place and like before, this is the error that we get when we try to apply migrations
No module named hooks for plugins
No module named hooks for artifacts
No module named hooks for alerting
No module named hooks for todos
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_LOADERS.
Operations to perform:
  Apply all migrations: authtoken, fir_nuggets, fir_alerting, fir_artifacts, sessions, admin, sites, auth, fir_todos, contenttypes, incidents
Running migrations:
  Rendering model states... DONE
  Applying fir_alerting.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1050, "Table 'incidents_categorytemplate' already exists")

Could you point us in the right direction?
Thank you
Claudiu

**Comment by gaelmuller** [comment]
Sorry for the late answer ... Are you still having this issue ?

It appears you are in a weird state where some of the migrations are not correctly marked as applied. You could try running the following command before trying to apply migrations again:

````
manage.py migrate --fake fir_alerting
````

**Comment by keoni161** [comment]
Hi.
We've done that. Afterwards we could no longer apply permissions on the database and no users could view the incidents.
We have made a clean install.
Thank you
Claudiu
