### ISSUE TITLE
Errors after latest upgrade

### ISSUE THREAD

**Issue by benjimons** [certsocietegenerale/FIR#153]
When including the abuse plugin now get the following:

```
 ./manage.py  migrate --settings fir.config.production
No module named hooks for plugins
No module named hooks for artifacts
No module named hooks for alerting
No module named hooks for todos
No module named hooks for api
No module named hooks for relations
No module named hooks for celery
No module named hooks for email
No module named hooks for abuse
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/FIR/fir/urls.py", line 28, in <module>
    urlpatterns.append(url('^{}/'.format(app_name), include(app_urls, namespace=app_name)))
  File "/usr/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/FIR/fir_abuse/urls.py", line 3, in <module>
    from fir_abuse import views
  File "/opt/FIR/fir_abuse/views.py", line 15, in <module>
    from fir_artifacts_enrichment.models import ArtifactEnrichment
  File "/opt/FIR/fir_artifacts_enrichment/models.py", line 8, in <module>
    class ArtifactEnrichment(models.Model):
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class fir_artifacts_enrichment.models.ArtifactEnrichment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by gaelmuller** [comment]
We did not communicate on these new plugins because they lack documentation for now.

In order to use `fir_abuse`, you need to also include `fir_artifacts_enrichment` in your installed apps, which doesn't seem to be the case here. Be warned that in order to enable `fir_artifacts_enrichment`, you need a running Redis instance at the moment.
