### ISSUE TITLE
bleach module error

### ISSUE THREAD

**Issue by eab12345** [certsocietegenerale/FIR#182]
Updated FIR on February 17 using the steps on the Wiki page.  Experiencing 502 Bad Gateway error after update

Commenting out the line "import bleach" in fir_plugins/templatetags/markdown.py fixes the issue

errors.logs
```
2017-02-18 05:17:54,698: base base.py:284(handle_uncaught_exception)
Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./incidents/views.py", line 135, in user_login
    return render(request, 'incidents/login.html')
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 142, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 159, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'fir_plugins.templatetags.markdown': No module named bleach
```

**Comment by gcrahay** [comment]
Install the new requirements:
```
(fir-env)# pip install -r requirements.txt
```

**Comment by eab12345** [comment]
@gcrahay That did the trick, thank you. Will need to remember that in the future.
