### ISSUE TITLE
 global name 'messages' is not defined

### ISSUE THREAD

**Issue by Mackousko12** [certsocietegenerale/FIR#198]
Hi,

When users change their password, they get error message i.e password not changed but then the logout and login they are able to login with new password. So password is changed at the backend but wrong message is displayed.

[23/May/2017 13:18:00] "POST /user/password/change HTTP/1.1" 500 15631
Internal Server Error: /user/password/change
Traceback (most recent call last):
  File "/home/wasim/env-FIR/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wasim/env-FIR/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wasim/env-FIR/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/wasim/env-FIR/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 42, in inner
    return func(request, *args, **kwargs)
  File "/home/wasim/FIR/incidents/views.py", line 2254, in user_change_password
    messages.error(request, form.errors)
NameError: global name 'messages' is not defined

Any help is greatly appreciated.

Thanks

Wasim

**Comment by Augustin-FL** [comment]
Fixed in https://github.com/certsocietegenerale/FIR/commit/bf144f6b7b2c3279db48b5ef11677d9680b92cf1
This issue can be closed
