### ISSUE TITLE
add file get error on docker if file contains no ascii char

### ISSUE THREAD

**Issue by lprat** [certsocietegenerale/FIR#227]
Hi
I get error when i upload file to incident:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "./fir_api/views.py", line 81, in upload
    f = handle_uploaded_file(file_obj, description, incident)
  File "./fir_artifacts/files.py", line 39, in handle_uploaded_file
    f.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1059, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1019, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 968, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py", line 311, in pre_save
    file.save(file.name, file, save=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 63, in save
    name = self._save(name, content)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 256, in _save
    _file.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 193-194: ordinal not in range(128)
```

I tried multi solutions (add env LC_TYPE, LC_LANG, LANG, PYTHONIOENCODING), but only one work, and it's ugly patch.
```
/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py 356,358c356
<                             try:
<                                 _file.write(chunk.encode("utf-8"))
<                             except:
<                                 _file.write(chunk)           
---
>                                 _file.write(chunk)
```
Do you have a best way to fix?
Thank you.

**Comment by Augustin-FL** [comment]
This issue has been fixed when FIR was ported to python3
