### ISSUE TITLE
Docker build: RuntimeError: Model class fir_todos.models.TodoItem doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by HazCod** [certsocietegenerale/FIR#60]
Step 14 : RUN ./manage.py migrate &&     ./manage.py loaddata incidents/fixtures/seed_data.json &&     ./manage.py loaddata incidents/fixtures/dev_users.json &&     cp fir/urls.py.sample fir/urls.py
 ---> Running in 4c4f1d21688a

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/fir/fir/urls.py", line 6, in <module>
    from incidents import views
  File "/home/fir/incidents/views.py", line 39, in <module>
    from fir_todos.models import TodoListTemplate
  File "/home/fir/fir_todos/models.py", line 6, in <module>
    class TodoItem(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class fir_todos.models.TodoItem doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by gaelmuller** [comment]
Thank you for reporting this issue. This should be fixed now.

**Comment by HazCod** [comment]
We're getting there :)

```
Step 12 : RUN ./manage.py migrate &&     ./manage.py loaddata incidents/fixtures/seed_data.json &&     ./manage.py loaddata incidents/fixtures/dev_users.json &&     cp fir/urls.py.sample fir/urls.py
 ---> Running in 7a6694d464f2
Operations to perform:
  Apply all migrations: authtoken, fir_artifacts, sessions, admin, sites, auth, contenttypes, incidents
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying authtoken.0001_initial... OK
  Applying incidents.0001_initial... OK
  Applying fir_artifacts.0001_initial... OK
  Applying fir_artifacts.0002_create_artifacts... OK
  Applying fir_artifacts.0003_auto_20160119_1131... OK
  Applying fir_artifacts.0002_artifactwhitelistitem... OK
  Applying fir_artifacts.0004_merge... OK
  Applying incidents.0002_link_incidents_to_artifacts... OK
  Applying incidents.0003_copy_file_artifact_data... OK
  Applying incidents.0004_delete_old_artifact_file... OK
  Applying incidents.0002_auto_20150907_1147... OK
  Applying incidents.0005_merge... OK
  Applying incidents.0003_auto_20160119_1021... OK
  Applying incidents.0006_merge... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
Installed 68 object(s) from 1 fixture(s)
Installed 3 object(s) from 1 fixture(s)
cp: cannot stat 'fir/urls.py.sample': No such file or directory
The command '/bin/sh -c ./manage.py migrate &&     ./manage.py loaddata incidents/fixtures/seed_data.json &&     ./manage.py loaddata incidents/fixtures/dev_users.json &&     cp fir/urls.py.sample fir/urls.py' returned a non-zero code: 1
```

**Comment by gaelmuller** [comment]
I'm sorry I do not have docker to validate it right now. Could you retry ?

**Comment by HazCod** [comment]
Can confirm it works now, thanks!
