### ISSUE TITLE
ValueError: Cannot serialize

### ISSUE THREAD

**Issue by er587** [certsocietegenerale/FIR#66]
I'm having a issue with migrations after I change the folder name and added my own app. Have you seen this issue before ?  I did not change any of the FIR models. This is my second migration and the initial. 

 Add field incident to attribute
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    self.write_migration_files(changes)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 178, in write_migration_files
    migration_string = writer.as_string()
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/db/migrations/writer.py", line 167, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/db/migrations/writer.py", line 124, in serialize
    _write(arg_name, arg_value)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/db/migrations/writer.py", line 88, in _write
    arg_string, arg_imports = MigrationWriter.serialize(_arg_value)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/db/migrations/writer.py", line 357, in serialize
    item_string, item_imports = cls.serialize(item)
  File "/Users/er/Desktop/sec_prod/lib/python2.7/site-packages/django/db/migrations/writer.py", line 540, in serialize
    "topics/migrations/#migration-serializing" % (value, get_docs_version())
ValueError: Cannot serialize: <class incidents.models.FIRModel at 0x105acde20>
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/1.9/topics/migrations/#migration-serializing

**Comment by gaelmuller** [comment]
Could you provide us with more information ?

What folder did you rename ? What command are you running ? It seems the failing command might be makemigrations for you custom app.

If this is the case, please provide the code you are using for your app's models.

**Comment by er587** [comment]
I renamed FIR-master to sec_prod, installed the requirements, added a basic app that uses CBV and references your Incidents models as a Foreign key. Then I ran  makemigrations and I got the error.   

class Domain(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    domainname = models.CharField(max_length=256)
    slug = models.SlugField(blank=True, unique=False)
    ticket = models.ForeignKey(Incident) 
    comments = models.TextField(max_length=1024, blank=True, null=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.domainname

    def get_absolute_url(self):
        return reverse ("domain_detail", kwargs={"pk": self.pk}

**Comment by gaelmuller** [comment]
Did you resolve this issue ?

I'm closing this since this is related to your custom code, but do not hesitate to reply if you still need help on this. Please however properly format your code with GitHub Markdown so that it is more readable. Your previous code snipper seems incomplete.

**Comment by er587** [comment]
I found out how to reproduce the error. It happens if you download the app fresh and then delete all the migrations.  I don’t know if this is a good thing to do or not, but I was trying to make a clean production ready environment.  - I’m send you this information, just in case it comes up again. 

Here is the step by step of what I did to reproduce this error.  

get https://github.com/certsocietegenerale/FIR/archive/master.zip
unzip master.zip
virtualenv .
source bin/activate
pip install -r FIR-master/requirements.txt
pip install psycopg2
vi FIR-master/fir/settings.py  # set database to postgresql
cd FIR-master/
find -name "000*" -delete  # delete migrations from github code
python manage.py migrate  
python manage.py makemigrations

Migrations for 'incidents':
  0001_initial.py:
    - Create model Attribute
    - Create model BaleCategory
    - Create model BusinessLine
    - Create model Comments
    - Create model Incident
    - Create model IncidentCategory
    - Create model IncidentTemplate
    - Create model Label
    - Create model LabelGroup
    - Create model Log
    - Create model Profile
    - Create model ValidAttribute
    - Add field group to label
    - Add field actor to incidenttemplate
    - Add field category to incidenttemplate
    - Add field concerned_business_lines to incidenttemplate
    - Add field detection to incidenttemplate
    - Add field plan to incidenttemplate
    - Add field actor to incident
    - Add field artifacts to incident
    - Add field category to incident
    - Add field concerned_business_lines to incident
    - Add field detection to incident
    - Add field main_business_lines to incident
    - Add field opened_by to incident
    - Add field plan to incident
    - Add field action to comments
    - Add field incident to comments
    - Add field opened_by to comments
    - Add field incident to attribute
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    self.write_migration_files(changes)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 178, in write_migration_files
    migration_string = writer.as_string()
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 167, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 124, in serialize
    _write(arg_name, arg_value)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 88, in _write
    arg_string, arg_imports = MigrationWriter.serialize(_arg_value)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 357, in serialize
    item_string, item_imports = cls.serialize(item)
  File "/home/er/firapp/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 540, in serialize
    "topics/migrations/#migration-serializing" % (value, get_docs_version())
ValueError: Cannot serialize: <class incidents.models.FIRModel at 0x7f1eca45fc80>
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/1.9/topics/migrations/#migration-serializing
