### ISSUE TITLE
Incident creation via API call

### ISSUE THREAD

**Issue by aleksf** [certsocietegenerale/FIR#79]
Hi,

I've upgraded fir to latest and have been trying (unsuccessfully) to create an incident via the API call. 

I pass following json

> 
{
	"detection": 8,
    	"opened_by": {
        	"username": "toor",
        	"email": "",
        	"groups": []
    	},
	"file_set": [],
	"date": "2015-11-18T15:47:42",
	"is_starred": false,
	"subject": "API test",
	"description": "API test",
	"severity": 3,
	"is_incident": false,
	"is_major": false,
	"status": "C",
	"confidentiality": 1,
	"category": {
		"id": 1,
		"name": "Wire Fraud",
		"is_major": false,
		"bale_subcategory": 1
	}
}
> 

When I pass my username, I get HTTP 400 in response:

HTTP 400 Bad Request
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "opened_by": {
        "username": [
            "A user with that username already exists."
        ]
    }
}

When I don't pass username, I get an error message that it can't be null and when I specify some garbage as a value, I get this in the error log

`Internal Server Error: /api/incidents
Traceback (most recent call last):
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "./fir_api/views.py", line 45, in perform_create
    instance = serializer.save(opened_by=self.request.user)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    raise_errors_on_nested_writes('create', self, validated_data)
  File "/data/local/www/env-FIR/lib/python2.7/site-packages/rest_framework/serializers.py", line 724, in raise_errors_on_nested_writes
    class_name=serializer.__class__.__name__
AssertionError: The `.create()` method does not support writable nestedfields by default.
Write an explicit `.create()` method for serializer `fir_api.serializers.IncidentSerializer`, or set `read_only=True` on nested serializer fields.`

Is this expected behavior? If not, please provide instructions around creating the incident via API.

**Comment by kevthehermit** [comment]
There is a temporary fix in this issue that works around the error

https://github.com/certsocietegenerale/FIR/issues/68

**Comment by tomchop** [comment]
See main issue on #68
